[tool.black]
line-lenght = 80

[tool.ruff]
line-length = 80
exclude = [
    ".venv",
    ".idea",
    ".tests"
]

[tool.mypy]
exclude = [
    ".venv",
    ".idea",
    ".tests"
]

[[tool.mypy.overrides]]
module = ["*"]
ignore_missing_imports = true
